openapi: '3.1.1'
info:
  title: API АкваЛедСтрой
  version: '1.0'
servers:
  - url: https://api.server.test
paths: 
  /api/admin/login:
    post:
      responses:
        '200':
          description: OK
          headers:
            Set-Cookie:
              schema:
                type: string
              description: Идентификатор сессии
              example: SESSIONID=abcde12345
        '401': 
          description: Unauthorized
        '500':
          description: Внутренняя ошибка сервера
      requestBody:
        required: true
        content: 
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email: 
                  type: string
                password:
                  type: string
              required:
                - email
                - password
